const GET_VARIABLES = 'GET_VARIABLES';
const VARIABLES_RECEIVED = 'VARIABLES_RECEIVED';
const CREATE_VARIABLE = 'CREATE_VARIABLE';
const DELETE_VARIABLE = 'DELETE_VARIABLE';

export {
  GET_VARIABLES,
  VARIABLES_RECEIVED,
  CREATE_VARIABLE,
  DELETE_VARIABLE
};
