const GET_VARIABLES = 'GET_VARIABLES';
const VARIABLES_RECEIVED = 'VARIABLES_RECEIVED';
const CREATE_VARIABLE = 'CREATE_VARIABLE';
const EDIT_VARIABLE = 'EDIT_VARIABLE';
const CANCEL_EDIT = 'CANCEL_EDIT';
const DELETE_VARIABLE = 'DELETE_VARIABLE';

export {
  GET_VARIABLES,
  VARIABLES_RECEIVED,
  CREATE_VARIABLE,
  EDIT_VARIABLE,
  CANCEL_EDIT,
  DELETE_VARIABLE
};
